name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Berkeley DB
      run: sudo apt-get install -y libdb-dev
    - name: Install MariaDB client dev
      run: sudo apt-get install -y libmariadb-dev
    - name: Install GCC
      run: sudo apt-get install -y gcc
    - name: Install Other stuff
      run: sudo apt-get install -y mariadb-server mariadb-client dovecot-mysql dovecot-imapd dovecot-submissiond dovecot-pop3d
    - name: make makefiles
      working-directory: ./postfix
      run: make -f Makefile.init makefiles "CCARGS=-DHAS_MYSQL -I/usr/local/mysql/include -DUSE_SASL_AUTH" "AUXLIBS_MYSQL=-L/usr/lib/x86_64-linux-gnu/ -lmariadbclient -lz -lm -lssl -lcrypto" CCARGS="-DUSE_SASL_AUTH -DDEF_SERVER_SASL_TYPE=\"dovecot\" -DUSE_TLS" dynamicmaps=yes AUXLIBS="-lssl -lcrypto"
    - name: make 
      working-directory: ./postfix
      run: make -j3
      
